apiVersion: v2
description: XWiki is a free wiki software platform written in Java with a design emphasis on extensibility. XWiki is an enterprise wiki. It includes WYSIWYG editing, OpenDocument based document import/export, semantic annotations and tagging, and advanced permissions management.
name: xwiki
version: 1.0-SNAPSHOT
appVersion: 11.10.4
type: application
keywords:
- xwiki
home: http://xwiki.org
icon: hhttps://www.xwiki.org/xwiki/bin/download/Main/Logo/logo-x.png
sources:
- https://github.com/xwiki-contrib/docker-xwiki
maintainers:
- name: Ashish Sharma
  email: sharma.ashish960@gmail.com
- name: Ludovic Dubost
  email: ludovic@xwiki.com
- name: Guilherme Sautner
  email: guilherme.sautner@xwiki.com
dependencies:
  - name: mysql
    repository: https://charts.helm.sh/stable
    version: 1.4.0
    condition: mysql.enabled
  - name: postgresql
    repository: https://charts.helm.sh/stable
    version: 7.6.0
    condition: postgresql.enabled
