# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: xwiki
  pullPolicy: IfNotPresent
## Image Tag useful when externalDB is been used
  tag: ''
service:
  portName: node
  name: http
  type: LoadBalancer
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 3000m
    memory: 6000Mi
  requests:
    cpu: 500m
    memory: 3000Mi
env: 
  JAVA_OPTS: "-Xmx2048m"
##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/mysql
##
mysql:
 ## Whether to deploy a mysql server. Set false for a different database.
  enabled: true
  mysqlRootPassword: xwiki
  mysqlUser: xwiki
  mysqlPassword: xwiki
  mysqlDatabase: xwiki
  imageTag: 5.7
  configurationFiles:
    mysql.cnf: |-
      [client]
      default-character-set = utf8mb4
      
      [mysqld]
      character-set-server = utf8mb4
      collation-server = utf8mb4_bin
      explicit_defaults_for_timestamp = 1
      
      [mysql]
      default-character-set = utf8mb4
##
## MySql chart configuration
##
## https://github.com/helm/charts/tree/master/stable/postgresql
##
postgresql:
 ## Whether to deploy a postgresql server. Set false for a different database.
  enabled: false
  postgresqlUsername: xwiki
  postgresqlPassword: xwiki
  postgresqlDatabase: xwiki
  image:
    tag: 11.3.0-debian-9-r38
  #persistence:
  #  size: 8Gi

##
## For custom mysql and postgres database. Use externalDB. 
## Would be used only if postgres and mysql is disabled.
## Set the image tag if want to use externalDB
##
externalDB:
  password: ''
  user: ''
  database: ''
  host: ''

##
## To use external solr enable solr, provide host and port
##
solr:
  enabled: true
  host: localhost
  port: 8983

# To use ingress for routing set ingress.enabled value to true and istio.enabled value to false
ingress:
  enabled: true
  issuer: dev-issuer
  className: ""
  annotations: 
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/rewrite-target: /
  hosts: 
    - host: ""
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: secret-tls
  #    hosts:
  #      - xwiki.local

# To use istio for routing set istio.enabled value to true and ingress.enabled value to false
istio:
  enabled: false
  host: "*"

storage: "500Mi"
storageClassName: ""
storageAccessMode: "ReadWriteMany"

## Read about PostDistribution budget at https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
## Use only on a clustered setup
podDisruptionBudget:
  enabled: false
  minAvailable: 1
  # maxUnavailable: 1

# Reference: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# Reference: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
  # - key: "key"
  #   operator: "Equal"
  #   value: "value"
  #   effect: "NoSchedule"

# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/e2e-az-name
  #         operator: In
  #         values:
  #         - e2e-az1
  #         - e2e-az2

customConfigs:
  # Properties key that exists, replace in line is done with value here defined. 
  # If key don't exists, this key and value will be appended in that specific file. 
  # This files are list of key: value that are translated as key=value in that file.
  #xwiki.cfg:
    # 
  #xwiki.properties:
    # 
