apiVersion: v1
kind: Service
metadata:
  name:  {{ include "xwiki.fullname" . }}
  labels:
    {{- include "xwiki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  sessionAffinity: ClientIP
  selector:
    {{- include "xwiki.selectorLabels" . | nindent 4 }}